/**
 * CS 키워드 사전 + 제목에서 키워드 추출
 *
 * longest-first 정렬로 "Large Language Model"이 "Language Model"보다 먼저 매칭.
 * word boundary (\b)로 부분 매칭 방지.
 */

export const KEYWORD_CATEGORIES: Record<string, string[]> = {
  "LLM & Language Models": [
    "Large Language Model",
    "Language Model",
    "LLM",
    "GPT",
    "ChatGPT",
    "Instruction Tuning",
    "RLHF",
    "In-Context Learning",
    "Chain-of-Thought",
    "Prompt",
    "Fine-Tuning",
    "Pretraining",
    "Pre-Training",
  ],
  "Generative Models": [
    "Diffusion Model",
    "Diffusion",
    "Text-to-Image",
    "Image Generation",
    "Video Generation",
    "Flow Matching",
    "Score Matching",
    "Generative",
    "GAN",
    "VAE",
    "Autoregressive",
  ],
  "Transformer & Attention": [
    "Vision Transformer",
    "Transformer",
    "Self-Attention",
    "Attention",
    "ViT",
    "BERT",
  ],
  "Graph Neural Networks": [
    "Graph Neural Network",
    "Knowledge Graph",
    "Graph Transformer",
    "GNN",
    "GCN",
    "Message Passing",
    "Graph",
  ],
  "Reinforcement Learning": [
    "Reinforcement Learning",
    "Reward Model",
    "Multi-Agent",
    "Policy Optimization",
    "RL",
  ],
  "Computer Vision": [
    "Object Detection",
    "Semantic Segmentation",
    "Instance Segmentation",
    "Segmentation",
    "Point Cloud",
    "Depth Estimation",
    "Image Restoration",
    "Super-Resolution",
    "3D Gaussian",
    "NeRF",
    "3D",
  ],
  NLP: [
    "Machine Translation",
    "Summarization",
    "Question Answering",
    "Sentiment Analysis",
    "Named Entity Recognition",
    "Relation Extraction",
    "Text Classification",
    "Information Extraction",
  ],
  "Robustness & Safety": [
    "Adversarial",
    "Robustness",
    "Fairness",
    "Bias",
    "Safety",
    "Alignment",
    "Backdoor",
    "Watermark",
    "Jailbreak",
  ],
  Efficiency: [
    "Mixture of Experts",
    "Knowledge Distillation",
    "Quantization",
    "Pruning",
    "Compression",
    "Low-Rank",
    "LoRA",
    "Sparse",
    "MoE",
    "Efficient",
  ],
  "Representation Learning": [
    "Contrastive Learning",
    "Self-Supervised",
    "Representation Learning",
    "Foundation Model",
    "Pre-Training",
    "Multimodal",
    "Embedding",
    "CLIP",
  ],
  "Federated & Privacy": [
    "Federated Learning",
    "Differential Privacy",
    "Privacy",
  ],
  Optimization: [
    "Optimization",
    "Convergence",
    "Gradient Descent",
  ],
  "Retrieval & Agents": [
    "Retrieval-Augmented",
    "RAG",
    "Agent",
    "Autonomous",
  ],
  "Data & Benchmarks": [
    "Benchmark",
    "Dataset",
    "Data Augmentation",
  ],
  "Transfer & Adaptation": [
    "Zero-Shot",
    "Few-Shot",
    "Transfer Learning",
    "Domain Adaptation",
    "Continual Learning",
    "Meta-Learning",
  ],
  // === Systems ===
  "Operating Systems": [
    "Operating System",
    "Kernel",
    "Microkernel",
    "Container",
    "Serverless",
    "Virtualization",
    "Disaggregation",
    "Memory Management",
    "Storage",
    "File System",
    "Scheduling",
    "RDMA",
    "SmartNIC",
    "FPGA",
    "CXL",
  ],
  "Cloud & Distributed": [
    "Cloud",
    "Microservice",
    "Distributed",
    "Consensus",
    "Replication",
    "Load Balancing",
    "Fault Tolerance",
    "Consistency",
    "Key-Value Store",
    "MapReduce",
    "Dataflow",
    "Stream Processing",
  ],
  // === Architecture ===
  "Computer Architecture": [
    "Accelerator",
    "GPU",
    "TPU",
    "NPU",
    "RISC-V",
    "Cache",
    "Prefetch",
    "Memory Hierarchy",
    "Out-of-Order",
    "Pipeline",
    "Speculative",
    "Branch Prediction",
    "DRAM",
    "Processing-in-Memory",
    "PIM",
    "Chiplet",
    "NoC",
    "Interconnect",
    "ASIC",
    "Reconfigurable",
    "Near-Data Processing",
    "DNN Accelerator",
  ],
  // === Security ===
  "Cryptography & Security": [
    "Encryption",
    "Homomorphic",
    "Zero-Knowledge",
    "Multi-Party Computation",
    "MPC",
    "Lattice",
    "Post-Quantum",
    "Signature",
    "Hash",
    "Blockchain",
    "Smart Contract",
    "Vulnerability",
    "Fuzzing",
    "Malware",
    "Intrusion Detection",
    "Access Control",
    "Authentication",
    "Side-Channel",
    "Trusted Execution",
    "SGX",
    "TEE",
    "Secure Computation",
    "TLS",
    "PKI",
  ],
  // === Networks ===
  "Networking": [
    "Congestion Control",
    "TCP",
    "Routing",
    "Software-Defined Networking",
    "SDN",
    "NFV",
    "5G",
    "6G",
    "IoT",
    "Edge Computing",
    "CDN",
    "Datacenter",
    "Data Center",
    "Network Function",
    "Programmable Switch",
    "P4",
    "Wireless",
    "Cellular",
    "Spectrum",
    "Latency",
    "Throughput",
    "Bandwidth",
    "QoS",
  ],
  // === Database ===
  "Database Systems": [
    "Query Optimization",
    "Query Processing",
    "Transaction",
    "ACID",
    "Index",
    "B-Tree",
    "LSM",
    "OLAP",
    "OLTP",
    "Data Warehouse",
    "Data Lake",
    "ETL",
    "SQL",
    "NoSQL",
    "NewSQL",
    "Column Store",
    "Vector Database",
    "Embedding Index",
    "Approximate Query",
    "Join",
    "Cardinality Estimation",
    "Learned Index",
  ],
  // === Software Engineering ===
  "Software Engineering": [
    "Code Generation",
    "Code Review",
    "Bug Detection",
    "Debugging",
    "Testing",
    "Test Generation",
    "Static Analysis",
    "Program Analysis",
    "Formal Verification",
    "Model Checking",
    "Software Maintenance",
    "Refactoring",
    "Code Clone",
    "Technical Debt",
    "CI/CD",
    "DevOps",
    "Code Completion",
    "Copilot",
    "LLM for Code",
    "APR",
    "Automated Program Repair",
  ],
  // === HCI ===
  "HCI & Interaction": [
    "User Study",
    "Usability",
    "Accessibility",
    "Haptic",
    "Gesture",
    "Eye Tracking",
    "Mixed Reality",
    "Augmented Reality",
    "Virtual Reality",
    "AR",
    "VR",
    "XR",
    "Wearable",
    "Conversational",
    "Chatbot",
    "Crowdsourcing",
    "Visualization",
    "Visual Analytics",
  ],
  // === Graphics ===
  "Computer Graphics": [
    "Rendering",
    "Ray Tracing",
    "Global Illumination",
    "Mesh",
    "Texture",
    "Simulation",
    "Physics-Based",
    "Fluid",
    "Deformable",
    "Animation",
    "Motion Capture",
    "Gaussian Splatting",
    "Radiance Field",
    "Neural Rendering",
    "Reconstruction",
    "Shape",
  ],
  // === PL ===
  "Programming Languages": [
    "Type System",
    "Type Theory",
    "Compiler",
    "JIT",
    "Garbage Collection",
    "Memory Safety",
    "Concurrency",
    "Parallelism",
    "Functional Programming",
    "Dependent Type",
    "Proof Assistant",
    "SMT",
    "SAT",
    "Abstract Interpretation",
    "Program Synthesis",
    "DSL",
  ],
  // === Robotics ===
  "Robotics & Control": [
    "Robot",
    "Manipulation",
    "Grasping",
    "Navigation",
    "SLAM",
    "Localization",
    "Motion Planning",
    "Path Planning",
    "Sim-to-Real",
    "Imitation Learning",
    "Autonomous Driving",
    "Self-Driving",
    "Drone",
    "UAV",
    "Humanoid",
    "Legged Robot",
  ],
  // === Theory ===
  "Algorithms & Theory": [
    "Approximation Algorithm",
    "Randomized Algorithm",
    "Online Algorithm",
    "Streaming Algorithm",
    "Sublinear",
    "NP-Hard",
    "Complexity",
    "Lower Bound",
    "Upper Bound",
    "Combinatorial",
    "Linear Programming",
    "Convex",
    "Matroid",
    "Submodular",
    "Parameterized",
    "Fixed-Parameter",
  ],
  // === Real-Time & Embedded ===
  "Real-Time & Embedded": [
    "Real-Time",
    "Embedded",
    "Worst-Case",
    "WCET",
    "Deadline",
    "Schedulability",
    "Mixed-Criticality",
    "Cyber-Physical",
    "CPS",
    "Automotive",
  ],
};

// Flatten and sort longest-first for greedy matching
export const KEYWORDS: string[] = Object.values(KEYWORD_CATEGORIES)
  .flat()
  // Deduplicate
  .filter((v, i, a) => a.indexOf(v) === i)
  .sort((a, b) => b.length - a.length);

// Pre-compiled regex patterns (case-insensitive, word-boundary)
const KEYWORD_PATTERNS: { keyword: string; regex: RegExp }[] = KEYWORDS.map(
  (kw) => ({
    keyword: kw,
    regex: new RegExp(
      `\\b${kw.replace(/[-/\\^$*+?.()|[\]{}]/g, "\\$&")}\\b`,
      "i",
    ),
  }),
);

/**
 * 논문 제목에서 매칭되는 키워드를 추출
 */
export function extractKeywords(title: string): string[] {
  const found: string[] = [];
  for (const { keyword, regex } of KEYWORD_PATTERNS) {
    if (regex.test(title)) {
      found.push(keyword);
    }
  }
  return found;
}
