#!/usr/bin/env python3
"""
best-papers.json에서 tags가 비어있는 논문에 자동으로 태그 생성
paper_title 기반 키워드 추출 (CS 도메인 사전 매칭)
"""
import json
import re

INPUT_FILE = "src/infrastructure/seed/best-papers.json"

# CS 도메인 키워드 사전 (긴 구문 우선 매칭)
KEYWORD_PATTERNS = [
    # === Machine Learning / Deep Learning ===
    (r"\b(large language model|llm)s?\b", "LLM"),
    (r"\blarge language models?\b", "LLM"),
    (r"\btransformer\b", "Transformer"),
    (r"\battention mechanism\b", "Attention"),
    (r"\bself.attention\b", "Attention"),
    (r"\bdiffusion model\b", "Diffusion Models"),
    (r"\bscore.based\b", "Diffusion Models"),
    (r"\bgenerative adversarial\b", "GAN"),
    (r"\b(gan|gans)\b", "GAN"),
    (r"\breinforcement learning\b", "Reinforcement Learning"),
    (r"\bdeep reinforcement\b", "Reinforcement Learning"),
    (r"\brl\b", "Reinforcement Learning"),
    (r"\bfederated learning\b", "Federated Learning"),
    (r"\bcontrastive learning\b", "Contrastive Learning"),
    (r"\bself.supervised\b", "Self-Supervised Learning"),
    (r"\bmeta.learning\b", "Meta-Learning"),
    (r"\bfew.shot\b", "Few-Shot Learning"),
    (r"\bzero.shot\b", "Zero-Shot Learning"),
    (r"\btransfer learning\b", "Transfer Learning"),
    (r"\bfine.tun(ing|e)\b", "Fine-Tuning"),
    (r"\bpre.train(ing|ed)\b", "Pre-Training"),
    (r"\bprompt\b", "Prompt Learning"),
    (r"\bin.context learning\b", "In-Context Learning"),
    (r"\binstruction tun\b", "Instruction Tuning"),
    (r"\bknowledge distill\b", "Knowledge Distillation"),
    (r"\bneural network\b", "Neural Networks"),
    (r"\bdeep learning\b", "Deep Learning"),
    (r"\brepresentation learning\b", "Representation Learning"),
    (r"\bembedding\b", "Embeddings"),
    (r"\bgraph neural\b", "Graph Neural Networks"),
    (r"\bgnn\b", "Graph Neural Networks"),
    (r"\brecurrent neural\b", "RNN"),
    (r"\blstm\b", "RNN"),
    (r"\bautoencoder\b", "Autoencoders"),
    (r"\bvariational\b", "Variational Methods"),
    (r"\bnormali[sz]ing flow\b", "Normalizing Flows"),
    (r"\bactive learning\b", "Active Learning"),
    (r"\bcurriculum learning\b", "Curriculum Learning"),
    (r"\bmulti.task\b", "Multi-Task Learning"),
    (r"\bmulti.modal\b", "Multimodal Learning"),
    (r"\boptimi[sz](ation|er|ing)\b", "Optimization"),
    (r"\bgradient\b", "Optimization"),
    (r"\bcalibrat\b", "Calibration"),
    (r"\buncertaint\b", "Uncertainty"),
    (r"\bbayesian\b", "Bayesian Methods"),
    (r"\bgaussian process\b", "Gaussian Processes"),
    (r"\banomaly detection\b", "Anomaly Detection"),
    (r"\boutlier\b", "Anomaly Detection"),

    # === Computer Vision ===
    (r"\bobject detection\b", "Object Detection"),
    (r"\bimage (segmentation|segment)\b", "Image Segmentation"),
    (r"\bsemantic segmentation\b", "Image Segmentation"),
    (r"\binstance segmentation\b", "Image Segmentation"),
    (r"\bimage (generation|synthesis|generat)\b", "Image Generation"),
    (r"\bimage (classification|recogni[sz])\b", "Image Classification"),
    (r"\bvisual (question|grounding|reasoning)\b", "Visual Reasoning"),
    (r"\bvision.language\b", "Vision-Language"),
    (r"\bvideo (understanding|recogni|classif|action)\b", "Video Understanding"),
    (r"\baction recogni\b", "Action Recognition"),
    (r"\bpose estimation\b", "Pose Estimation"),
    (r"\bdepth estimation\b", "Depth Estimation"),
    (r"\b3d (reconstruction|understanding|object|scene|point)\b", "3D Vision"),
    (r"\bpoint cloud\b", "3D Vision"),
    (r"\bneural radiance\b", "NeRF"),
    (r"\bnerf\b", "NeRF"),
    (r"\bface (recognition|detection|synthesis|generat)\b", "Face Recognition"),
    (r"\btracking\b", "Object Tracking"),
    (r"\boptical flow\b", "Optical Flow"),
    (r"\bstereo\b", "Stereo Vision"),
    (r"\bsaliency\b", "Saliency"),
    (r"\bcaption(ing)?\b", "Image Captioning"),
    (r"\bmedical imag\b", "Medical Imaging"),

    # === NLP ===
    (r"\bmachine translation\b", "Machine Translation"),
    (r"\bneural machine translation\b", "Machine Translation"),
    (r"\bquestion answering\b", "Question Answering"),
    (r"\btext (generation|generat)\b", "Text Generation"),
    (r"\btext classif\b", "Text Classification"),
    (r"\bsentiment\b", "Sentiment Analysis"),
    (r"\bnamed entity\b", "Named Entity Recognition"),
    (r"\binformation retrieval\b", "Information Retrieval"),
    (r"\binformation extraction\b", "Information Extraction"),
    (r"\brelation extraction\b", "Relation Extraction"),
    (r"\bknowledge graph\b", "Knowledge Graph"),
    (r"\bdialogue\b", "Dialogue Systems"),
    (r"\bconversation\b", "Dialogue Systems"),
    (r"\bsummariz\b", "Summarization"),
    (r"\btext summar\b", "Summarization"),
    (r"\bcoreference\b", "Coreference Resolution"),
    (r"\bword embedding\b", "Word Embeddings"),
    (r"\bword2vec\b", "Word Embeddings"),
    (r"\blanguage model(ing)?\b", "Language Models"),
    (r"\bspeech recogni\b", "Speech Recognition"),
    (r"\bspeech synthesis\b", "Speech Synthesis"),
    (r"\btext.to.speech\b", "Speech Synthesis"),
    (r"\bmachine reading\b", "Machine Reading"),
    (r"\bcross.lingual\b", "Cross-Lingual"),
    (r"\bmultilingual\b", "Multilingual NLP"),
    (r"\bsemantic pars\b", "Semantic Parsing"),
    (r"\btextual entailment\b", "Textual Entailment"),
    (r"\bnli\b", "Natural Language Inference"),
    (r"\bnatural language inference\b", "Natural Language Inference"),
    (r"\btokeniz\b", "Tokenization"),
    (r"\bcode generation\b", "Code Generation"),
    (r"\bprogram synthesis\b", "Code Generation"),

    # === Security ===
    (r"\bvulnerabilit\b", "Vulnerability Detection"),
    (r"\bbug detect\b", "Bug Detection"),
    (r"\bfuzz(ing)?\b", "Fuzzing"),
    (r"\badversarial (attack|example|training|robust)\b", "Adversarial ML"),
    (r"\brobust(ness)?\b", "Robustness"),
    (r"\bmalware\b", "Malware Detection"),
    (r"\bintrusion detection\b", "Intrusion Detection"),
    (r"\bdifferential privacy\b", "Differential Privacy"),
    (r"\bprivacy.preserving\b", "Privacy"),
    (r"\bprivacy\b", "Privacy"),
    (r"\bencrypt\b", "Cryptography"),
    (r"\bcryptograph\b", "Cryptography"),
    (r"\bblockchain\b", "Blockchain"),
    (r"\bsmart contract\b", "Smart Contracts"),
    (r"\bauthenticat\b", "Authentication"),
    (r"\baccess control\b", "Access Control"),
    (r"\bside.channel\b", "Side-Channel Attacks"),
    (r"\bphishing\b", "Phishing"),
    (r"\bransomware\b", "Ransomware"),
    (r"\bdeepfake\b", "Deepfake Detection"),
    (r"\bwatermark\b", "Watermarking"),
    (r"\btaint\b", "Taint Analysis"),
    (r"\bsymbolic execut\b", "Symbolic Execution"),

    # === Systems ===
    (r"\bdistributed (system|computing|training|learning)\b", "Distributed Systems"),
    (r"\bcloud computing\b", "Cloud Computing"),
    (r"\bcontainer\b", "Containerization"),
    (r"\bkubernetes\b", "Kubernetes"),
    (r"\bmemory (management|allocat|safety)\b", "Memory Management"),
    (r"\bcache\b", "Caching"),
    (r"\bschedul(ing|er)\b", "Scheduling"),
    (r"\bconcurren(cy|t)\b", "Concurrency"),
    (r"\bparallel(ism|ization)?\b", "Parallel Computing"),
    (r"\boperating system\b", "Operating Systems"),
    (r"\bkernel\b", "Operating Systems"),
    (r"\bvirtuali[sz]\b", "Virtualization"),
    (r"\bfile system\b", "File Systems"),
    (r"\bstorage\b", "Storage Systems"),
    (r"\bflash\b", "Storage Systems"),
    (r"\bssd\b", "Storage Systems"),
    (r"\benergy.efficient\b", "Energy Efficiency"),
    (r"\bpower consumption\b", "Energy Efficiency"),
    (r"\bhardware\b", "Hardware"),
    (r"\bfpga\b", "FPGA"),
    (r"\bgpu\b", "GPU Computing"),
    (r"\bheterogeneous\b", "Heterogeneous Computing"),
    (r"\bcompiler\b", "Compilers"),
    (r"\bprogramming language\b", "Programming Languages"),
    (r"\btype (system|inference|check)\b", "Type Systems"),
    (r"\bstatic analy\b", "Static Analysis"),
    (r"\bprogram analy\b", "Program Analysis"),
    (r"\bprogram verif\b", "Program Verification"),
    (r"\bformal verif\b", "Formal Verification"),
    (r"\bmodel check\b", "Model Checking"),

    # === Databases ===
    (r"\bquery optim\b", "Query Optimization"),
    (r"\btransaction\b", "Transactions"),
    (r"\bindex(ing)?\b", "Indexing"),
    (r"\bdata(base)? management\b", "Database Management"),
    (r"\brelational\b", "Relational Databases"),
    (r"\bnosql\b", "NoSQL"),
    (r"\btime.series\b", "Time-Series Data"),
    (r"\bstream(ing)? process\b", "Stream Processing"),
    (r"\bdata warehouse\b", "Data Warehousing"),
    (r"\bolap\b", "OLAP"),
    (r"\bknowledge base\b", "Knowledge Base"),
    (r"\bgraph (database|query)\b", "Graph Databases"),
    (r"\bdata cleaning\b", "Data Quality"),
    (r"\bdata integrat\b", "Data Integration"),

    # === Networks ===
    (r"\bwireless\b", "Wireless Networks"),
    (r"\bwifi\b", "Wireless Networks"),
    (r"\b5g\b", "5G"),
    (r"\biot\b", "IoT"),
    (r"\bmobile (network|computing|edge)\b", "Mobile Computing"),
    (r"\bedge computing\b", "Edge Computing"),
    (r"\bfog computing\b", "Edge Computing"),
    (r"\brouting\b", "Network Routing"),
    (r"\bsdn\b", "Software-Defined Networking"),
    (r"\bnetwork (traffic|measur|monitor)\b", "Network Monitoring"),
    (r"\bnetwork secur\b", "Network Security"),
    (r"\bddos\b", "DDoS"),
    (r"\bprotocol\b", "Network Protocols"),
    (r"\blatency\b", "Latency Optimization"),
    (r"\bthroughput\b", "Network Performance"),
    (r"\bqos\b", "Quality of Service"),
    (r"\bp2p\b", "P2P Networks"),
    (r"\bcontent delivery\b", "CDN"),

    # === Algorithms ===
    (r"\bgraph (algorithm|theory|learning)\b", "Graph Algorithms"),
    (r"\bapproximation algorithm\b", "Approximation Algorithms"),
    (r"\bonline (algorithm|learning)\b", "Online Algorithms"),
    (r"\brandom(ized)?\b", "Randomized Algorithms"),
    (r"\bcomputational complexity\b", "Computational Complexity"),
    (r"\bnp.hard\b", "Computational Complexity"),
    (r"\bdata structure\b", "Data Structures"),
    (r"\bsort(ing)?\b", "Sorting"),
    (r"\bsearch(ing)?\b", "Search Algorithms"),
    (r"\bcombinatorial optim\b", "Combinatorial Optimization"),
    (r"\bconvex optim\b", "Convex Optimization"),
    (r"\binteger program\b", "Integer Programming"),
    (r"\blinear program\b", "Linear Programming"),
    (r"\bsatisfia\b", "SAT"),
    (r"\bgame theor\b", "Game Theory"),
    (r"\bauction\b", "Auction Theory"),
    (r"\bmechanism design\b", "Mechanism Design"),
    (r"\bmarkov\b", "Markov Models"),
    (r"\bdynamic program\b", "Dynamic Programming"),
    (r"\bstreaming algorithm\b", "Streaming Algorithms"),

    # === HCI / Visualization ===
    (r"\buser (interface|experience|study|interact)\b", "HCI"),
    (r"\bui\b", "HCI"),
    (r"\bux\b", "HCI"),
    (r"\baugmented reality\b", "Augmented Reality"),
    (r"\bvirtual reality\b", "Virtual Reality"),
    (r"\bxr\b", "Extended Reality"),
    (r"\btouch(screen)?\b", "Touch Interfaces"),
    (r"\bgesturesd?\b", "Gesture Recognition"),
    (r"\baccessi\b", "Accessibility"),
    (r"\bvisuali[sz]ation\b", "Data Visualization"),
    (r"\bcrowdsourc\b", "Crowdsourcing"),
    (r"\bsocial (network|media|comput)\b", "Social Networks"),
    (r"\bwearable\b", "Wearable Computing"),
    (r"\bsmart home\b", "Smart Home"),
    (r"\bsmart (city|urban)\b", "Smart Cities"),
    (r"\bhuman.robot\b", "Human-Robot Interaction"),
    (r"\brobot(ic)?\b", "Robotics"),
    (r"\bautonomous\b", "Autonomous Systems"),
    (r"\bself.driv\b", "Autonomous Vehicles"),
    (r"\bnavigat\b", "Navigation"),

    # === Software Engineering ===
    (r"\bcode review\b", "Code Review"),
    (r"\bcode (summar|search|clone|smell)\b", "Code Analysis"),
    (r"\btest(ing)? generat\b", "Test Generation"),
    (r"\bsoftware test\b", "Software Testing"),
    (r"\bbug (fix|repair|local)\b", "Bug Fixing"),
    (r"\brefactor\b", "Refactoring"),
    (r"\btechnical debt\b", "Technical Debt"),
    (r"\bmicroservice\b", "Microservices"),
    (r"\bapi (design|usage|misuse)\b", "API Design"),
    (r"\bdevops\b", "DevOps"),
    (r"\bcontinuous integrat\b", "CI/CD"),
    (r"\bopen source\b", "Open Source"),
    (r"\bgit\b", "Version Control"),
    (r"\bcode generat\b", "Code Generation"),
    (r"\bprogram repair\b", "Program Repair"),

    # === AI / Reasoning ===
    (r"\breason(ing)?\b", "Reasoning"),
    (r"\bplanning\b", "AI Planning"),
    (r"\bknowledge represent\b", "Knowledge Representation"),
    (r"\bontolog\b", "Ontology"),
    (r"\bsemantic web\b", "Semantic Web"),
    (r"\bexplain(able|ability)\b", "Explainable AI"),
    (r"\binterpret(able|ability)\b", "Explainable AI"),
    (r"\bfairness\b", "Fairness"),
    (r"\bbias\b", "Bias"),
    (r"\btrustworthi\b", "Trustworthy AI"),
    (r"\bhallucinat\b", "Hallucination"),
    (r"\bagi\b", "AGI"),
    (r"\bautomated (machine learning|ml)\b", "AutoML"),
    (r"\bautoml\b", "AutoML"),
    (r"\bneural architect\b", "Neural Architecture Search"),
    (r"\bnas\b", "Neural Architecture Search"),
    (r"\bhyperparameter\b", "Hyperparameter Tuning"),
    (r"\bbenchmark\b", "Benchmarking"),
    (r"\bevaluat\b", "Evaluation"),
    (r"\bmulti.agent\b", "Multi-Agent Systems"),
    (r"\bagent\b", "AI Agents"),

    # === Additional ML Topics ===
    (r"\bdomain adapt\b", "Domain Adaptation"),
    (r"\bsemi.supervised\b", "Semi-Supervised Learning"),
    (r"\bweakly.supervised\b", "Weakly Supervised Learning"),
    (r"\bunsupervised\b", "Unsupervised Learning"),
    (r"\bcluster(ing)?\b", "Clustering"),
    (r"\bclassif(y|ier|ication)\b", "Classification"),
    (r"\bregress(ion)?\b", "Regression"),
    (r"\bdetect(ion|or)\b", "Detection"),
    (r"\bgenerat(ive|ion|e)\b", "Generative Models"),
    (r"\bsynthes(is|ize)\b", "Synthesis"),
    (r"\baugmentat\b", "Data Augmentation"),
    (r"\bdata.efficient\b", "Data Efficiency"),
    (r"\blong.tail\b", "Long-Tail Learning"),
    (r"\bimbalanced\b", "Class Imbalance"),
    (r"\bpolicy (gradient|optim|learn)\b", "Policy Optimization"),
    (r"\bppo\b", "Policy Optimization"),
    (r"\bactor.critic\b", "Policy Optimization"),
    (r"\breward\b", "Reinforcement Learning"),
    (r"\bexploration\b", "Exploration"),
    (r"\bmodel.based\b", "Model-Based Methods"),
    (r"\boffline rl\b", "Offline RL"),
    (r"\bimitation learn\b", "Imitation Learning"),
    (r"\bworld model\b", "World Models"),
    (r"\bscal(e|ing|ability)\b", "Scalability"),
    (r"\befficient\b", "Efficiency"),
    (r"\bcompress(ion)?\b", "Model Compression"),
    (r"\bpruning\b", "Model Pruning"),
    (r"\bquantiz\b", "Quantization"),
    (r"\bsparse\b", "Sparse Methods"),
    (r"\bmixture of expert\b", "Mixture of Experts"),
    (r"\bmoe\b", "Mixture of Experts"),
    (r"\bfoundation model\b", "Foundation Models"),
    (r"\bmultimodal\b", "Multimodal Learning"),
    (r"\baudio\b", "Audio Processing"),
    (r"\bsound\b", "Audio Processing"),
    (r"\bmusic\b", "Music Generation"),
    (r"\bpoint cloud\b", "3D Vision"),
    (r"\bmesh\b", "3D Vision"),
    (r"\bsurface reconstruct\b", "3D Reconstruction"),

    # === Cryptography (more) ===
    (r"\blattice\b", "Lattice Cryptography"),
    (r"\bpost.quantum\b", "Post-Quantum Cryptography"),
    (r"\bzero.knowledge\b", "Zero-Knowledge Proofs"),
    (r"\bzkp\b", "Zero-Knowledge Proofs"),
    (r"\bproof system\b", "Proof Systems"),
    (r"\bsecure (computation|multi.party)\b", "Secure Computation"),
    (r"\bhomomorphic\b", "Homomorphic Encryption"),
    (r"\bmpc\b", "Secure Computation"),
    (r"\bntru\b", "Lattice Cryptography"),
    (r"\bsha\b", "Hash Functions"),
    (r"\bhash function\b", "Hash Functions"),
    (r"\bdigital signature\b", "Digital Signatures"),

    # === Robotics / Manufacturing ===
    (r"\bgrasping\b", "Robotic Manipulation"),
    (r"\bmanipulat\b", "Robotic Manipulation"),
    (r"\bmotion (planning|control)\b", "Motion Planning"),
    (r"\blocomotion\b", "Robot Locomotion"),
    (r"\badditive manufacturing\b", "Additive Manufacturing"),
    (r"\b3d print\b", "Additive Manufacturing"),
    (r"\bfabrication\b", "Fabrication"),
    (r"\bsensor\b", "Sensors"),
    (r"\bslam\b", "SLAM"),
    (r"\bsimulation.to.real\b", "Sim-to-Real"),
    (r"\bsim2real\b", "Sim-to-Real"),
    (r"\bdexterous\b", "Dexterous Manipulation"),
    (r"\bdeformable\b", "Deformable Objects"),

    # === PL / Compilers ===
    (r"\babstract interpret\b", "Abstract Interpretation"),
    (r"\bdomain.specific language\b", "Domain-Specific Languages"),
    (r"\bdsl\b", "Domain-Specific Languages"),
    (r"\bintermediate represent\b", "Compiler IR"),
    (r"\bcode optim\b", "Code Optimization"),
    (r"\bloop optim\b", "Loop Optimization"),
    (r"\bvectoriz\b", "Vectorization"),
    (r"\bautomatic paralleliz\b", "Automatic Parallelization"),
    (r"\bjit\b", "JIT Compilation"),
    (r"\bgarbage collect\b", "Garbage Collection"),
    (r"\btype inference\b", "Type Inference"),
    (r"\bdependent type\b", "Dependent Types"),
    (r"\beffect system\b", "Effect Systems"),
    (r"\bproof assistant\b", "Proof Assistants"),
    (r"\bcoq\b", "Proof Assistants"),
    (r"\bisabelle\b", "Proof Assistants"),
    (r"\bsemantics\b", "Programming Language Semantics"),

    # === Entailment / Logic ===
    (r"\bentailment\b", "Textual Entailment"),
    (r"\blogic(al)?\b", "Logic"),
    (r"\bsat solver\b", "SAT Solving"),
    (r"\bsmt\b", "SMT Solving"),
    (r"\bconstraint (programm|satisf)\b", "Constraint Programming"),
    (r"\bprobabilistic (programm|model|infer)\b", "Probabilistic Programming"),

    # === Cooperative/Multi-Agent ===
    (r"\bcooperat(ive|ion)\b", "Cooperative Systems"),
    (r"\bcoordinat\b", "Coordination"),
    (r"\bswarm\b", "Swarm Intelligence"),
    (r"\bdecentral(ized)?\b", "Decentralized Systems"),
    (r"\bnash equilib\b", "Nash Equilibrium"),

    # === Quantum ===
    (r"\bquantum (computing|circuit|algorithm|error|machine)\b", "Quantum Computing"),
    (r"\bquantum\b", "Quantum Computing"),
    (r"\bqubit\b", "Quantum Computing"),

    # === Debugging / Tools ===
    (r"\bdebug(ger|ging)?\b", "Debugging"),
    (r"\bprofil(er|ing)\b", "Profiling"),
    (r"\bmonitor(ing)?\b", "Monitoring"),
    (r"\btracing\b", "Tracing"),
    (r"\blog(ging)?\b", "Logging"),
    (r"\bperformance (analysis|optim|model)\b", "Performance Analysis"),

    # === Word Sense / Lexical ===
    (r"\bword sense\b", "Word Sense Disambiguation"),
    (r"\blexical\b", "Lexical Semantics"),
    (r"\bmorpholog\b", "Morphology"),
    (r"\bsyntax\b", "Syntax"),
    (r"\bparsing\b", "Parsing"),
    (r"\bgrammar\b", "Grammar"),

    # === Packing / Binary ===
    (r"\bpacking\b", "Binary Analysis"),
    (r"\bbinary analy\b", "Binary Analysis"),
    (r"\breverse engineer\b", "Reverse Engineering"),
    (r"\bdecompil\b", "Decompilation"),
    (r"\bdisassembl\b", "Disassembly"),

    # === Availability / Reliability ===
    (r"\bavailability\b", "Reliability"),
    (r"\bfault toleran\b", "Fault Tolerance"),
    (r"\bresilience\b", "Resilience"),
    (r"\breliabilit\b", "Reliability"),
    (r"\brecovery\b", "Recovery"),
    (r"\bcheckpoint\b", "Checkpointing"),
    (r"\bconsistency\b", "Consistency"),

    # === HCI (more) ===
    (r"\bempathic\b", "HCI"),
    (r"\bneurodiverse\b", "Accessibility"),
    (r"\bhaptic\b", "Haptics"),
    (r"\btangible\b", "Tangible Interfaces"),
    (r"\bembodied\b", "Embodied Interaction"),
    (r"\bsocial robot\b", "Social Robotics"),
    (r"\bchild(ren)?\b", "Child-Computer Interaction"),
    (r"\bolder adult\b", "Aging & Technology"),
    (r"\bmental health\b", "Mental Health Technology"),
    (r"\bwellbeing\b", "Wellbeing"),
    (r"\bhealth(care)?\b", "Health Informatics"),
    (r"\bteaching\b", "Educational Technology"),
    (r"\beducation\b", "Educational Technology"),
    (r"\blearn(er|ing) environment\b", "Educational Technology"),
    (r"\bgaming\b", "Gaming"),
    (r"\bgame design\b", "Game Design"),
    (r"\bparticipatory\b", "Participatory Design"),
    (r"\bco.design\b", "Participatory Design"),
    (r"\bprobing\b", "Design Probes"),
    (r"\bqualitative study\b", "Qualitative Research"),
    (r"\buser stud\b", "User Studies"),
    (r"\binterview\b", "Qualitative Research"),
    (r"\bethno\b", "Ethnography"),

    # === Android / Mobile Security ===
    (r"\bandroid\b", "Android Security"),
    (r"\bmobile (secur|malware|app)\b", "Mobile Security"),
    (r"\bapp (analysis|detect|repack)\b", "App Security"),

    # === Specific Topics ===
    (r"\brecommender\b", "Recommender Systems"),
    (r"\brecommendation\b", "Recommender Systems"),
    (r"\bcollaborative filter\b", "Collaborative Filtering"),
    (r"\bclick.through\b", "CTR Prediction"),
    (r"\bcomputer.aided\b", "Computer-Aided Design"),
    (r"\bbioinformat\b", "Bioinformatics"),
    (r"\bgenomics\b", "Genomics"),
    (r"\bprotein\b", "Protein Structure"),
    (r"\bdrug (discover|design)\b", "Drug Discovery"),
    (r"\bclimate\b", "Climate Science"),
    (r"\benergy\b", "Energy Systems"),
    (r"\bfinancial\b", "Financial Computing"),
    (r"\bfraud detect\b", "Fraud Detection"),
    (r"\be.commerce\b", "E-Commerce"),
    (r"\bsupply chain\b", "Supply Chain"),
    (r"\blocali[sz]ation\b", "Localization"),
    (r"\bsimulat\b", "Simulation"),
    (r"\bdigital twin\b", "Digital Twins"),
    (r"\bweb (mining|scraping|crawl)\b", "Web Mining"),
    (r"\bweb application\b", "Web Applications"),
    (r"\bsearch engine\b", "Search Engines"),
    (r"\bads\b", "Advertising"),
]

def extract_tags(title: str) -> list:
    title_lower = title.lower()
    matched = []
    seen = set()
    for pattern, tag in KEYWORD_PATTERNS:
        if re.search(pattern, title_lower) and tag not in seen:
            matched.append(tag)
            seen.add(tag)
        if len(matched) >= 5:
            break
    return matched


def main():
    with open(INPUT_FILE, encoding="utf-8") as f:
        papers = json.load(f)

    no_tags = [(i, p) for i, p in enumerate(papers) if not p.get("tags") or p["tags"] == []]
    print(f"태그 없는 논문: {len(no_tags)}개")

    filled = 0
    empty = 0
    for i, paper in no_tags:
        tags = extract_tags(paper["paper_title"])
        papers[i]["tags"] = tags
        if tags:
            filled += 1
        else:
            empty += 1

    with open(INPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(papers, f, ensure_ascii=False, indent=2)

    print(f"완료: {filled}개 태그 생성, {empty}개 매칭 없음")
    print(f"pnpm seed 실행해서 DB 반영하세요.")


if __name__ == "__main__":
    main()
